### PR TITLE
Feat1 : Add lbl1 to print version info on UI

### PR DESCRIPTION
**Pull request by opsonin**
Add lbl1 to print version info on UI

### CODE REVIEW

**Comment by opsonin** [comment]
Request for authorization of Pull Request

**Review by seaguall — COMMENTED** [review]
Finished Review

**Comment by seaguall** [comment]
Merge pull request #1 from seaguall/test-pr

**Review by seaguall — APPROVED** [review]
apprive

**Comment by seaguall** [comment]
I approved your request

**Review by seaguall — APPROVED** [review]
approve re-review

**Pull request merged**
